### ISSUE TITLE
Docker setup help with --add-host=dockerhost:

### ISSUE THREAD

**Issue by aptonline** [matijse/eufy-ha-mqtt-bridge#28]
I'm trying to setup eufy-ha-mqtt-bridge using docker and running into an issue when running the command.  I have my MQTT broker running on the same box (192.168.1.12) as I'm trying to run eufy-ha-mqtt-bridge as well as my HA install.

If I change the `dockerhost` in the docker run command to `192.168.1.12` I get an error:

`invalid argument "192.168.1.12:" for "--add-host" flag: invalid IP address in add-host: ""
`

If I change the `dockerhost` to `dockerhost:192.168.1.12` it runs ok and I can see the sensors and camera entities appear in HA and I can see the raw MQTT topics in MQTTfx but I don't see any updates.

Can someone clarify how I configure the `dockerhost` parameter correctly?

**Comment by matijse** [comment]
You should not change the command in the example. It makes the host `dockerhost` (left side of the : ) available inside the container, with a value of the output of the command after `dockerhost:` in the command (right side of the : ). This makes sure `dockerhost` dynamically has the correct value inside the docker container.

Then you can use `dockerhost` instead of the direct IP adress in the configuration that is used in the Docker container, so your MQTT broker can be reached at `mqtt://dockerhost:1883` instead of `mqtt://192.168.x.x:1883`.

**Comment by aptonline** [comment]
Thanks for your reply, If I run the command as is I still get the same error:

`invalid argument "dockerhost:" for "--add-host" flag: invalid IP address in add-host: ""`

**Comment by matijse** [comment]
Does this command output something?
```
docker network inspect --format='{{range .IPAM.Config}}{{.Gateway}}{{end}}' bridge
```

What OS are you using? 

Depending on your setup it will probably work if you just remove the line with `--add-host...` completely and just use `mqtt://192.168.1.12:1883` as the MQTT url

If you use Mac, you can also try removing the line and use `mqtt://host.docker.internal:1883` as the MQTT url.

**Comment by aptonline** [comment]
I’ll give that a try. I’m using docker in a Synology NAS.

**Comment by aptonline** [comment]
I’ve removed the `—add host` parameter and it seems to be working.

thanks for the support.
