### ISSUE TITLE
Floodlight camera T8420 no longer works

### ISSUE THREAD

**Issue by mikedrawback** [matijse/eufy-ha-mqtt-bridge#36]
The event type for the floodlight is different from other cameras.  The event type is "3". 

notificationType for generic motion detection is now bound to "3101", so I no longer get notifications for motion detected by the floodlight camera.

How should this be implemented? A custom type like FLOODLIGHT_MOTION_DETECTED?

```
id,station_sn,device_sn,type,payload
YYYYYYY,YYYYYYYYYYYYYYYY,,3,"{""id"":""XXXXXXX"",""from"":""XXXXXXXXXXXX"",""to"":""XXXXXXXXXXXXXXXXX"",""category"":""com.oceanwing.battery.cam"",""persistentId"":""X:XXXXXXXXXXXXXXXXX"",""ttl"":3600,""sent"":""1609404148865"",""payload"":{""payload"":{""a"":1,""s"":""XXXXXXXXXXXXXXXX"",""c"":0,""p"":""20201231034227"",""k"":37,""n"":""Garage Floodlight""},""station_sn"":""XXXXXXXXXXXXXXXX"",""push_time"":""1609404148779"",""type"":""3"",""content"":""Garage Floodlight: Motion detected"",""event_time"":""1609404147885"",""title"":"""",""device_sn"":"""",""google.c.sender.id"":""XXXXXXXX""}}"
```

**Comment by matijse** [comment]
I changed the way other notifications are detected, because it seemed all of them were only distinguishable by the "content" string in the notification.  (For example the door sensor had the same type for both open and closed messages).

I thought all camera's did report the content as "{camera name}: Motion is detected", but in your payload I see "Garage Floodlight: Motion detected" (no "is"). That's why it is not detected anymore. I will add that it also triggers on "Motion detected". (new version coming in a bit)

**Comment by mikedrawback** [comment]
Great, thank you!

**Comment by mikedrawback** [comment]
Confirmed this is fixed! Thanks @matijse
