### ISSUE TITLE
Only publishing events to MQTT on startup

### ISSUE THREAD

**Issue by aptonline** [matijse/eufy-ha-mqtt-bridge#51]
Recently I am only seeing events in MQTT from `eufy-ha-mqtt-brigde` when the container first starts up. No other communication is received if I use MQTT.fx to monitor. 

This seems to have started when I updated to the latest version (0.2.11).  For reference I am using 2.0.7 of Mosquitto running on the same server as `eufy-ha-mqtt-brigde` with a [slightly modified docker command](https://github.com/matijse/eufy-ha-mqtt-bridge/issues/28#issuecomment-763032872) due to my setup.

**Comment by matijse** [comment]
Since you still receive messages on startup, the connection details should be good (for example IP is still the same). 

Are you sure push messages are sent by the Eufy app? Only if a message is sent it is received and processed by the integration. Do you receive messages on your phone? Check that you don't have settings in the Eufy app that prevent messages, for example when the alarm mode is set to Home.

If that is the case, can you share the log output for the time you know a message should have been received? (log files in the data folder)

**Comment by aptonline** [comment]
Thanks for the update.  Happy to close.
